import { type NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Nav"

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </>
  );
};

export default Home;


